import React, { useRef } from 'react';
import { X, Printer, Download, Scale } from 'lucide-react';
import { CourtCase } from '../types.js';
import { toDisplayDate } from '../utils/date.js';
import { exportToPdf } from '../utils/export.js';
import courtEmblem from '../assets/images/court_emblem_insignia_1790276040697.jpg';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  cases: CourtCase[];
  courtName?: string;
  reportHeader?: string;
  reportFooter?: string;
}

export const PrintPreviewModal: React.FC<Props> = ({
  isOpen,
  onClose,
  title,
  cases,
  courtName = 'Court of Judicial Magistrate & Bench Officer',
  reportHeader = 'COURT CASE DIARY — PROCEEDINGS RECORD',
  reportFooter = 'Generated by Court Dairy — Court Case Diary & Management System'
}) => {
  const printAreaRef = useRef<HTMLDivElement>(null);

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handlePdfDownload = () => {
    exportToPdf(cases, {
      title,
      courtName,
      filterDescription: `${cases.length} records printed`
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-6 bg-black/85 backdrop-blur-sm animate-fadeIn">
      <div className="bg-neutral-900 border border-neutral-700 rounded-xl shadow-2xl max-w-5xl w-full flex flex-col max-h-[95vh] overflow-hidden">
        {/* Controls Toolbar (hidden on print) */}
        <div className="no-print px-5 py-3 border-b border-neutral-800 bg-neutral-950 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Printer className="w-4 h-4 text-amber-500" />
            <h2 className="text-sm font-semibold text-neutral-100">
              Print Preview: {title}
            </h2>
            <span className="text-xs text-neutral-400 font-mono">
              ({cases.length} records)
            </span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePdfDownload}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-neutral-800 hover:bg-neutral-700 text-neutral-200 text-xs rounded border border-neutral-700 transition-colors"
            >
              <Download className="w-3.5 h-3.5 text-rose-400" />
              <span>Save as PDF</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-4 py-1.5 bg-amber-600 hover:bg-amber-500 text-neutral-950 font-semibold text-xs rounded shadow-sm transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print (System Dialog)</span>
            </button>

            <button
              onClick={onClose}
              className="p-1 text-neutral-400 hover:text-white rounded hover:bg-neutral-800 transition-colors ml-2"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Printable Preview Canvas (simulates official judicial paper) */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-8 bg-neutral-950 flex justify-center">
          <div
            ref={printAreaRef}
            className="print-content bg-white text-neutral-900 w-full max-w-[210mm] p-[12mm] rounded shadow-lg text-[10pt] font-serif leading-normal"
          >
            {/* Judicial Crest and Header */}
            <div className="text-center border-b-2 border-neutral-900 pb-3 mb-4">
              <div className="flex justify-center mb-2">
                <img
                  src={courtEmblem}
                  alt="Official Emblem"
                  className="w-12 h-12 rounded object-cover"
                  referrerPolicy="no-referrer"
                />
              </div>
              <h1 className="text-base sm:text-lg font-bold uppercase tracking-wider text-neutral-900 m-0">
                {courtName}
              </h1>
              <h2 className="text-xs sm:text-sm font-semibold tracking-wide text-neutral-800 mt-1 uppercase">
                {reportHeader}
              </h2>
              <div className="text-xs font-sans text-neutral-600 mt-1">
                <strong>Report Title:</strong> {title}
              </div>
              <div className="flex justify-between items-center text-[9pt] font-sans text-neutral-500 mt-2 pt-2 border-t border-neutral-300">
                <span>Total Listed Cases: <strong>{cases.length}</strong></span>
                <span>Date of Printing: <strong>{new Date().toLocaleDateString('en-GB')} {new Date().toLocaleTimeString()}</strong></span>
              </div>
            </div>

            {/* Official Data Table */}
            {cases.length === 0 ? (
              <div className="py-12 text-center text-neutral-500 italic">
                No case records found for this schedule.
              </div>
            ) : (
              <table className="w-full border-collapse text-[9pt] font-sans mb-4">
                <thead>
                  <tr className="bg-neutral-100 border-y-2 border-neutral-900">
                    <th className="py-2 px-1 text-center font-bold w-12 border-r border-neutral-300">Serial</th>
                    <th className="py-2 px-1 text-center font-bold w-20 border-r border-neutral-300">Case Date</th>
                    <th className="py-2 px-2 text-left font-bold w-28 border-r border-neutral-300">Case Number</th>
                    <th className="py-2 px-1 text-center font-bold w-20 border-r border-neutral-300">Result</th>
                    <th className="py-2 px-1 text-center font-bold w-20 border-r border-neutral-300">Dairy Date</th>
                    <th className="py-2 px-2 text-left font-bold border-r border-neutral-300">Description</th>
                    <th className="py-2 px-2 text-left font-bold w-36">Remarks</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-neutral-300 border-b border-neutral-900">
                  {cases.map((c) => (
                    <tr key={c.ID} className="break-inside-avoid">
                      <td className="py-1.5 px-1 text-center font-mono border-r border-neutral-200">
                        {c.SerialNo}
                      </td>
                      <td className="py-1.5 px-1 text-center font-mono border-r border-neutral-200">
                        {c.DisplayCaseDate || toDisplayDate(c.CaseDate)}
                      </td>
                      <td className="py-1.5 px-2 font-bold border-r border-neutral-200">
                        {c.CaseNumber}
                      </td>
                      <td className="py-1.5 px-1 text-center border-r border-neutral-200">
                        {c.Result}
                      </td>
                      <td className="py-1.5 px-1 text-center font-mono font-semibold border-r border-neutral-200">
                        {c.DisplayDairyDate || toDisplayDate(c.DairyDate)}
                      </td>
                      <td className="py-1.5 px-2 border-r border-neutral-200 break-words leading-tight">
                        {c.Description || '-'}
                      </td>
                      <td className="py-1.5 px-2 break-words text-neutral-700 leading-tight">
                        {c.Remarks || '-'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}

            {/* Official Print Sign-off Footer */}
            <div className="mt-8 pt-4 border-t border-neutral-400 flex justify-between items-end text-[9pt] font-sans text-neutral-600">
              <div>
                <div>{reportFooter}</div>
                <div className="text-[8pt] text-neutral-400 mt-0.5">
                  Court Dairy System · Offline Database Verified
                </div>
              </div>
              <div className="text-right">
                <div className="w-40 border-b border-neutral-900 mb-1"></div>
                <div className="font-semibold text-neutral-800">Bench Officer / Reader</div>
                <div className="text-[8pt]">Seal & Signature</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
