/**
 * Court Dairy — Professional Offline Desktop Court Case Diary & Management System
 * Built for Bench Officers and Court Administrators
 */

import React, { useState, useEffect, useCallback } from 'react';
import { DesktopTitleBar } from './components/DesktopTitleBar.js';
import { Sidebar } from './components/Sidebar.js';
import { TopBar } from './components/TopBar.js';
import { DashboardView } from './components/DashboardView.js';
import { CaseListView } from './components/CaseListView.js';
import { CaseFormModal } from './components/CaseFormModal.js';
import { CaseDetailModal } from './components/CaseDetailModal.js';
import { DeleteConfirmModal } from './components/DeleteConfirmModal.js';
import { AdvancedSearchView } from './components/AdvancedSearchView.js';
import { ReportsView } from './components/ReportsView.js';
import { PrintPreviewModal } from './components/PrintPreviewModal.js';
import { ResultManagementView } from './components/ResultManagementView.js';
import { UserManagementView } from './components/UserManagementView.js';
import { BackupRestoreView } from './components/BackupRestoreView.js';
import { SettingsView } from './components/SettingsView.js';
import { ImportModal } from './components/ImportModal.js';
import { KeyboardShortcutsModal } from './components/KeyboardShortcutsModal.js';
import { AboutModal } from './components/AboutModal.js';
import { SetupView } from './components/SetupView.js';
import { LoginView } from './components/LoginView.js';
import { ToastContainer } from './components/ToastContainer.js';

import {
  User,
  CourtCase,
  ResultOption,
  SystemSettings,
  DashboardData,
  Pagination,
  ToastMessage
} from './types.js';
import { api, getStoredToken, getStoredUser, clearStoredSession } from './services/api.js';
import { exportToExcel } from './utils/export.js';

export default function App() {
  // System status
  const [bootLoading, setBootLoading] = useState(true);
  const [setupRequired, setSetupRequired] = useState(false);
  const [currentUser, setCurrentUser] = useState<User | null>(null);

  // Active view
  const [currentView, setCurrentView] = useState<string>('dashboard');
  const [isDark, setIsDark] = useState<boolean>(() => {
    try {
      const saved = localStorage.getItem('court_dairy_theme');
      if (saved) return saved === 'dark';
    } catch {
      // ignore
    }
    return true;
  });

  // Sync DOM classes whenever isDark changes
  useEffect(() => {
    try {
      localStorage.setItem('court_dairy_theme', isDark ? 'dark' : 'light');
    } catch {
      // ignore
    }
    const root = document.documentElement;
    const body = document.body;
    if (isDark) {
      root.classList.add('dark');
      root.classList.remove('light');
      body.classList.add('dark');
      body.classList.remove('light');
    } else {
      root.classList.add('light');
      root.classList.remove('dark');
      body.classList.add('light');
      body.classList.remove('dark');
    }
  }, [isDark]);

  // Settings
  const [settings, setSettings] = useState<SystemSettings>({
    appName: 'Court Dairy',
    appSubtitle: 'Court Case Diary & Management System',
    courtName: 'Court of the Bench Officer & Judicial Magistrate',
    reportHeader: 'COURT CASE DIARY — PROCEEDINGS RECORD',
    reportFooter: 'Generated by Court Dairy — Court Case Diary & Management System',
    defaultResult: 'Pending',
    dateFormat: 'DD-MM-YYYY',
    upcomingDays: '14',
    theme: 'dark',
    autoBackup: 'Daily'
  });

  // Data states
  const [resultsList, setResultsList] = useState<ResultOption[]>([]);
  const [dashboardData, setDashboardData] = useState<DashboardData | null>(null);
  const [loadingDashboard, setLoadingDashboard] = useState(false);

  // Case Register states
  const [cases, setCases] = useState<CourtCase[]>([]);
  const [loadingCases, setLoadingCases] = useState(false);
  const [globalSearch, setGlobalSearch] = useState('');
  const [sortBy, setSortBy] = useState('SerialNo');
  const [sortOrder, setSortOrder] = useState('ASC');
  const [pagination, setPagination] = useState<Pagination>({
    page: 1,
    limit: 25,
    totalRecords: 0,
    totalPages: 1
  });
  const [nextSerial, setNextSerial] = useState(1);

  // Modals
  const [caseFormOpen, setCaseFormOpen] = useState(false);
  const [editingCase, setEditingCase] = useState<CourtCase | null>(null);
  const [detailCaseId, setDetailCaseId] = useState<number | null>(null);
  const [deleteConfirmItem, setDeleteConfirmItem] = useState<CourtCase | null>(null);
  const [deletingCase, setDeletingCase] = useState(false);

  const [printModalState, setPrintModalState] = useState<{
    isOpen: boolean;
    title: string;
    cases: CourtCase[];
  }>({
    isOpen: false,
    title: '',
    cases: []
  });

  const [importModalOpen, setImportModalOpen] = useState(false);
  const [shortcutsModalOpen, setShortcutsModalOpen] = useState(false);
  const [aboutModalOpen, setAboutModalOpen] = useState(false);

  // Toasts
  const [toasts, setToasts] = useState<ToastMessage[]>([]);

  const addToast = useCallback((type: 'success' | 'error' | 'info' | 'warning', message: string) => {
    const id = Math.random().toString(36).substring(2, 9);
    setToasts(prev => [...prev, { id, type, message }]);
    setTimeout(() => {
      setToasts(prev => prev.filter(t => t.id !== id));
    }, 4500);
  }, []);

  const dismissToast = (id: string) => {
    setToasts(prev => prev.filter(t => t.id !== id));
  };

  // Initial Boot Check
  useEffect(() => {
    const checkBoot = async () => {
      try {
        setBootLoading(true);
        const status = await api.getStatus();
        if (status.setupRequired) {
          setSetupRequired(true);
          setBootLoading(false);
          return;
        }

        const token = getStoredToken();
        const storedUser = getStoredUser();

        if (token && storedUser) {
          try {
            const me = await api.getMe();
            setCurrentUser(me.user);
          } catch {
            clearStoredSession();
            setCurrentUser(null);
          }
        }
      } catch (err) {
        console.error('Boot status error:', err);
      } finally {
        setBootLoading(false);
      }
    };

    checkBoot();

    const handleAuthExpired = () => {
      setCurrentUser(null);
      addToast('warning', 'Session expired. Please log in again.');
    };
    window.addEventListener('auth:expired', handleAuthExpired);
    return () => window.removeEventListener('auth:expired', handleAuthExpired);
  }, [addToast]);

  // Load user-authenticated initial metadata (settings, results)
  useEffect(() => {
    if (!currentUser) return;

    loadResults();
    loadSettings();
    loadDashboard();
    loadCases();
    loadNextSerial();
  }, [currentUser]);

  const loadResults = async () => {
    try {
      const list = await api.getResults();
      setResultsList(list);
    } catch (e) {
      console.warn(e);
    }
  };

  const loadSettings = async () => {
    try {
      const s = await api.getSettings();
      if (s && Object.keys(s).length > 0) {
        setSettings(prev => ({ ...prev, ...s }));
        if (s.theme) {
          setIsDark(s.theme === 'dark');
        }
      }
    } catch (e) {
      console.warn(e);
    }
  };

  const loadDashboard = async () => {
    try {
      setLoadingDashboard(true);
      const data = await api.getDashboard();
      setDashboardData(data);
    } catch (e) {
      console.warn(e);
    } finally {
      setLoadingDashboard(false);
    }
  };

  const loadCases = async (page = pagination.page, limit = pagination.limit, search = globalSearch, sort = sortBy, order = sortOrder) => {
    try {
      setLoadingCases(true);
      const res = await api.getCases({
        page,
        limit,
        search,
        sortBy: sort,
        sortOrder: order
      });
      setCases(res.records);
      setPagination(res.pagination);
    } catch (e) {
      console.warn(e);
    } finally {
      setLoadingCases(false);
    }
  };

  const loadNextSerial = async () => {
    try {
      const res = await api.getNextSerial();
      setNextSerial(res.nextSerial);
    } catch (e) {
      console.warn(e);
    }
  };

  const handleRefreshAll = () => {
    loadDashboard();
    loadCases();
    loadResults();
    loadNextSerial();
    addToast('info', 'Court dairy data refreshed from SQLite.');
  };

  // Keyboard Shortcuts Handler
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // If typing in input/textarea, ignore shortcuts except Esc
      const activeEl = document.activeElement;
      const isInput = activeEl?.tagName === 'INPUT' || activeEl?.tagName === 'TEXTAREA';

      if (e.key === 'Escape') {
        setCaseFormOpen(false);
        setDetailCaseId(null);
        setDeleteConfirmItem(null);
        setPrintModalState(prev => ({ ...prev, isOpen: false }));
        setImportModalOpen(false);
        setShortcutsModalOpen(false);
        setAboutModalOpen(false);
        return;
      }

      if (isInput) return;

      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'n') {
        e.preventDefault();
        setEditingCase(null);
        setCaseFormOpen(true);
      } else if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'f') {
        e.preventDefault();
        setCurrentView('advanced-search');
      } else if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'p') {
        e.preventDefault();
        setPrintModalState({
          isOpen: true,
          title: 'Court Diary Print Record',
          cases: cases.length > 0 ? cases : (dashboardData?.todayList || [])
        });
      } else if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'e') {
        e.preventDefault();
        if (cases.length > 0) {
          exportToExcel(cases, {
            title: 'Court_Dairy_Export',
            courtName: settings.courtName
          });
          addToast('success', 'Cases exported to Excel (.xlsx)');
        }
      } else if (e.key === 'F5') {
        e.preventDefault();
        handleRefreshAll();
      } else if (e.key === '?') {
        e.preventDefault();
        setShortcutsModalOpen(true);
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [cases, dashboardData, settings.courtName, addToast]);

  // CRUD Handlers
  const handleSaveCase = async (caseData: Partial<CourtCase>) => {
    const caseNum = caseData.CaseNumber || (caseData as any).caseNumber || '';
    if (caseData.ID) {
      await api.updateCase(caseData.ID, caseData);
      addToast('success', `Case #${caseNum} updated successfully.`);
    } else {
      await api.createCase(caseData);
      addToast('success', `Case #${caseNum} recorded in Court Dairy.`);
      setCurrentView('case-list');
    }
    loadCases();
    loadDashboard();
    loadNextSerial();
  };

  const handleDeleteConfirm = async () => {
    if (!deleteConfirmItem) return;
    try {
      setDeletingCase(true);
      await api.deleteCase(deleteConfirmItem.ID);
      addToast('success', `Case #${deleteConfirmItem.CaseNumber} deleted successfully.`);
      setDeleteConfirmItem(null);
      if (detailCaseId === deleteConfirmItem.ID) {
        setDetailCaseId(null);
      }
      loadCases();
      loadDashboard();
      loadNextSerial();
    } catch (err: any) {
      addToast('error', err.message || 'Failed to delete case.');
    } finally {
      setDeletingCase(false);
    }
  };

  const handleLogout = async () => {
    await api.logout();
    setCurrentUser(null);
    addToast('info', 'Logged out of Court Dairy.');
  };

  const handleSaveSettings = async (newSettings: SystemSettings) => {
    await api.updateSettings(newSettings);
    setSettings(newSettings);
    if (newSettings.theme) {
      setIsDark(newSettings.theme === 'dark');
    }
    addToast('success', 'Court & system settings saved.');
  };

  const handleToggleTheme = () => {
    const nextDark = !isDark;
    setIsDark(nextDark);
    const themeName = nextDark ? 'dark' : 'light';
    setSettings(prev => ({ ...prev, theme: themeName }));
    api.updateSettings({ ...settings, theme: themeName }).catch(console.warn);
    addToast('info', `Switched to ${nextDark ? 'Dark Theme' : 'Light Theme'}`);
  };

  // Rendering conditional screens
  if (bootLoading) {
    return (
      <div className="min-h-screen bg-neutral-950 flex flex-col items-center justify-center text-neutral-300 font-mono text-xs space-y-3 select-none">
        <div className="w-8 h-8 border-2 border-amber-500 border-t-transparent rounded-full animate-spin"></div>
        <span>Initializing Court Dairy Offline SQLite Engine...</span>
      </div>
    );
  }

  // First-run Administrator Setup
  if (setupRequired && !currentUser) {
    return (
      <>
        <SetupView
          onSetupComplete={(user) => {
            setSetupRequired(false);
            setCurrentUser(user);
          }}
          onToast={addToast}
        />
        <ToastContainer toasts={toasts} onDismiss={dismissToast} />
      </>
    );
  }

  // Login Screen
  if (!currentUser) {
    return (
      <>
        <LoginView
          onLoginSuccess={(user) => setCurrentUser(user)}
          onToast={addToast}
          courtName={settings.courtName}
        />
        <ToastContainer toasts={toasts} onDismiss={dismissToast} />
      </>
    );
  }

  // Main Desktop Application Shell
  return (
    <div className={`h-screen flex flex-col overflow-hidden bg-neutral-950 text-neutral-100 ${isDark ? 'dark' : 'light'}`}>
      {/* Desktop Window Title Bar */}
      <DesktopTitleBar appName={settings.appName} courtName={settings.courtName} />

      {/* Main Workspace Frame */}
      <div className="flex-1 flex overflow-hidden">
        {/* Modern Desktop Sidebar */}
        <Sidebar
          currentView={currentView}
          onNavigate={(view) => {
            if (view === 'new-case') {
              setEditingCase(null);
              setCaseFormOpen(true);
            } else if (view === 'about') {
              setAboutModalOpen(true);
            } else {
              setCurrentView(view);
            }
          }}
          currentUser={currentUser}
          onLogout={handleLogout}
          onOpenShortcuts={() => setShortcutsModalOpen(true)}
          todayCount={dashboardData?.statistics.todayCases || 0}
          upcomingCount={dashboardData?.statistics.upcomingCases || 0}
          overdueCount={dashboardData?.statistics.overdueCases || 0}
        />

        {/* Viewport Content Area */}
        <div className="flex-1 flex flex-col min-w-0 bg-neutral-950 overflow-hidden">
          {/* Top Bar Contract (3-Zone) */}
          <TopBar
            currentView={currentView}
            globalSearch={globalSearch}
            onGlobalSearchChange={(val) => {
              setGlobalSearch(val);
              if (currentView !== 'case-list') setCurrentView('case-list');
              loadCases(1, pagination.limit, val);
            }}
            onGlobalSearchSubmit={() => {
              if (currentView !== 'case-list') setCurrentView('case-list');
              loadCases(1, pagination.limit, globalSearch);
            }}
            onRefresh={handleRefreshAll}
            onNewCase={() => {
              setEditingCase(null);
              setCaseFormOpen(true);
            }}
            onPrintCurrent={() => {
              setPrintModalState({
                isOpen: true,
                title: `${settings.appName} — ${currentView.toUpperCase()}`,
                cases: cases.length > 0 ? cases : (dashboardData?.todayList || [])
              });
            }}
            isDark={isDark}
            onToggleTheme={handleToggleTheme}
          />

          {/* Active View Container */}
          <main className="flex-1 overflow-hidden bg-neutral-925">
            {currentView === 'dashboard' && (
              <DashboardView
                data={dashboardData}
                loading={loadingDashboard}
                onViewCase={(id) => setDetailCaseId(id)}
                onEditCase={(c) => {
                  setEditingCase(c);
                  setCaseFormOpen(true);
                }}
                onNavigate={(v) => setCurrentView(v)}
                onPrintPreview={(title, caseList) => {
                  setPrintModalState({
                    isOpen: true,
                    title,
                    cases: caseList
                  });
                }}
              />
            )}

            {currentView === 'case-list' && (
              <CaseListView
                cases={cases}
                pagination={pagination}
                loading={loadingCases}
                sortBy={sortBy}
                sortOrder={sortOrder}
                onSortChange={(col) => {
                  const newOrder = sortBy === col && sortOrder === 'ASC' ? 'DESC' : 'ASC';
                  setSortBy(col);
                  setSortOrder(newOrder);
                  loadCases(pagination.page, pagination.limit, globalSearch, col, newOrder);
                }}
                onPageChange={(p) => loadCases(p, pagination.limit, globalSearch)}
                onLimitChange={(l) => loadCases(1, l, globalSearch)}
                onViewCase={(id) => setDetailCaseId(id)}
                onEditCase={(c) => {
                  setEditingCase(c);
                  setCaseFormOpen(true);
                }}
                onDeleteCase={(c) => setDeleteConfirmItem(c)}
                onNewCase={() => {
                  setEditingCase(null);
                  setCaseFormOpen(true);
                }}
                onOpenImport={() => setImportModalOpen(true)}
                onPrintPreview={(title, caseList) => {
                  setPrintModalState({
                    isOpen: true,
                    title,
                    cases: caseList
                  });
                }}
                courtName={settings.courtName}
                userRole={currentUser.role}
              />
            )}

            {currentView === 'advanced-search' && (
              <AdvancedSearchView
                resultsList={resultsList}
                onViewCase={(id) => setDetailCaseId(id)}
                onEditCase={(c) => {
                  setEditingCase(c);
                  setCaseFormOpen(true);
                }}
                onPrintPreview={(title, caseList) => {
                  setPrintModalState({
                    isOpen: true,
                    title,
                    cases: caseList
                  });
                }}
                courtName={settings.courtName}
              />
            )}

            {currentView.startsWith('reports-') && (
              <ReportsView
                initialReportType={currentView.replace('reports-', '')}
                resultsList={resultsList}
                onViewCase={(id) => setDetailCaseId(id)}
                onPrintPreview={(title, caseList) => {
                  setPrintModalState({
                    isOpen: true,
                    title,
                    cases: caseList
                  });
                }}
                courtName={settings.courtName}
              />
            )}

            {currentView === 'admin-results' && (
              <ResultManagementView
                resultsList={resultsList}
                onRefresh={loadResults}
                onToast={addToast}
              />
            )}

            {currentView === 'admin-users' && (
              <UserManagementView
                currentUser={currentUser}
                onToast={addToast}
              />
            )}

            {currentView === 'admin-backup' && (
              <BackupRestoreView
                onToast={addToast}
                onRefreshAll={handleRefreshAll}
              />
            )}

            {currentView === 'admin-logs' && (
              <BackupRestoreView
                onToast={addToast}
                onRefreshAll={handleRefreshAll}
              />
            )}

            {currentView === 'admin-settings' && (
              <SettingsView
                settings={settings}
                resultsList={resultsList}
                onSaveSettings={handleSaveSettings}
                onToast={addToast}
              />
            )}
          </main>
        </div>
      </div>

      {/* Case Entry / Edit Modal */}
      <CaseFormModal
        isOpen={caseFormOpen}
        onClose={() => {
          setCaseFormOpen(false);
          setEditingCase(null);
        }}
        onSave={handleSaveCase}
        editingCase={editingCase}
        nextSerial={nextSerial}
        resultsList={resultsList}
      />

      {/* Case Details Dossier Modal */}
      <CaseDetailModal
        caseId={detailCaseId}
        isOpen={detailCaseId !== null}
        onClose={() => setDetailCaseId(null)}
        onEditCase={(c) => {
          setDetailCaseId(null);
          setEditingCase(c);
          setCaseFormOpen(true);
        }}
        onDeleteCase={(c) => setDeleteConfirmItem(c)}
        onPrintPreview={(title, caseList) => {
          setPrintModalState({
            isOpen: true,
            title,
            cases: caseList
          });
        }}
        resultsList={resultsList}
        onCaseUpdated={() => {
          loadCases();
          loadDashboard();
        }}
        onToast={addToast}
      />

      {/* Delete Confirmation Modal */}
      <DeleteConfirmModal
        isOpen={deleteConfirmItem !== null}
        onClose={() => setDeleteConfirmItem(null)}
        onConfirm={handleDeleteConfirm}
        caseItem={deleteConfirmItem}
        deleting={deletingCase}
      />

      {/* Print Preview Modal */}
      <PrintPreviewModal
        isOpen={printModalState.isOpen}
        onClose={() => setPrintModalState(prev => ({ ...prev, isOpen: false }))}
        title={printModalState.title}
        cases={printModalState.cases}
        courtName={settings.courtName}
        reportHeader={settings.reportHeader}
        reportFooter={settings.reportFooter}
      />

      {/* Data Import Modal */}
      <ImportModal
        isOpen={importModalOpen}
        onClose={() => setImportModalOpen(false)}
        onSuccess={() => {
          loadCases();
          loadDashboard();
          loadNextSerial();
        }}
        onToast={addToast}
      />

      {/* Keyboard Shortcuts Modal */}
      <KeyboardShortcutsModal
        isOpen={shortcutsModalOpen}
        onClose={() => setShortcutsModalOpen(false)}
      />

      {/* About Modal */}
      <AboutModal
        isOpen={aboutModalOpen}
        onClose={() => setAboutModalOpen(false)}
        appName={settings.appName}
        appSubtitle={settings.appSubtitle}
        courtName={settings.courtName}
      />

      {/* Toast Notifications */}
      <ToastContainer toasts={toasts} onDismiss={dismissToast} />
    </div>
  );
}
